program:
  overwrite: True
  log_dir: ./logs
trainer:
  gpus: 1
  min_epochs: 4
  max_epochs: 20
  benchmark: True
  enable_progress_bar: True
  precision: 16
  #auto_lr_find: True
  #auto_scale_batch_size: binsearch

experiment:
  task: "ccmeo"
  name: "ccmeo_tests"
  module:
    loss: "softbce"
    segmentation_model: "unet"
    encoder_name: "resnet50"
    encoder_weights: null
    encoder_output_stride: 16
    learning_rate: 5e-4
    learning_rate_schedule_patience: 6
    in_channels: 3
    num_classes: 1
    num_filters: 256
    ignore_zeros: True
    imagenet_pretraining: True
  datamodule:
    root_dir: "/home/remi/PycharmProjects/geo-deep-learning/data/"
    train_splits:
      - "trn.csv"
    val_splits:
      - "val.csv"
    test_splits:
      - "test.csv"
    patch_size: 512
    batch_size: 12
    num_workers: 4
    class_set: ${experiment.module.num_classes}
    use_prior_labels: False
