program:
  overwrite: True
trainer:
  min_epochs: 2
  max_epochs: 4
experiment:
  task: "potsdam"
  name: "potsdam_test"
  module:
    loss: "ce"
    segmentation_model: "unet"
    encoder_name: "resnet18"
    encoder_weights: "imagenet"
    encoder_output_stride: 16
    learning_rate: 1e-3
    learning_rate_schedule_patience: 2
    in_channels: 4
    num_classes: 6
    num_filters: 64
    ignore_zeros: False
  datamodule:
    root_dir: "/media/data/potsdam-vahingen/Potsdam"
    batch_size: 4
    num_workers: 4
    patch_size: 1024
